### ISSUE TITLE
Connecting a Postgres Database

### ISSUE THREAD

**Issue by amandewatnitrr** [amandewatnitrr/django-tutorial#4]
By default, I am using the Django default SQLite Database, and want to shift to Postgres.

**Comment by kiranrokkam09** [comment]
Hello @amandewatnitrr,

I am interested in working on the issue. Would it be possible for you to assign it to me?

**Comment by amandewatnitrr** [comment]
Sure, make sure to make changes in a separate branch, by your name, don't merge it to the master directly.

**Comment by amandewatnitrr** [comment]
This issue is assigned to @kiranrokkam09 .

**Comment by kiranrokkam09** [comment]
Hello @amandewatnitrr,

Have you already created a PostgreSQL database? If you have, could you please provide me with the details of the database?

**Comment by amandewatnitrr** [comment]
@kiranrokkam09 I haven't created one yet.

**Comment by kiranrokkam09** [comment]
@amandewatnitrr ok then let me create one for you.

**Comment by kiranrokkam09** [comment]
@amandewatnitrr I need your information to make an account on Railway.app, or you can create an account there and send me your information.
